#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)

. ${DIR}/init_homalg_starter

mkdir -p checksums

echo "Creating $start_script"

echo "export DIR=${DIR}" > $start_script
echo ". ${DIR}/homalg_starter" >> $start_script
echo "echo Loading workspace:" >> $start_script
echo "echo ${DIR}/checksums/homalg_workspace_git" >> $start_script
echo "${gap_bin} -R -L ${DIR}/checksums/homalg_workspace \"\$@\"" >> $start_script
chmod +x $start_script
