#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)

. ${DIR}/init_homalg_starter

mkdir -p checksums

echo "Creating $start_script_git"

echo "export DIR=${DIR}" > $start_script_git
echo ". ${DIR}/homalg_starter_git" >> $start_script_git
echo "echo Loading workspace:" >> $start_script_git
echo "echo ${DIR}/checksums/homalg_workspace_git" >> $start_script_git
echo "${gap_bin} -R -L ${DIR}/checksums/homalg_workspace_git \"\$@\"" >> $start_script_git
chmod +x $start_script_git
