#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)

. ${DIR}/init_homalg_starter

mkdir -p checksums

echo "export DIR=${DIR}" > $start_script
echo ". ${DIR}/homalg_starter" >> $start_script
echo "${gap_bin} -R -L ${DIR}/checksums/homalg_workspace \"\$@\"" >> $start_script
chmod +x $start_script
