#!/bin/bash

. ${DIR}/init_homalg_starter

checker=""

for mod in ${homalg_project_modules}; do
    if [ -r ${package_directory}/homalg_project/${mod}/PackageInfo.g ]; then
        X=$(md5sum ${package_directory}/homalg_project/${mod}/PackageInfo.g | sed 's/ //g')
        
        if [ -f ${DIR}/checksums/${mod}PackageInfo.checksum ]; then
            Y=$(cat ${DIR}/checksums/${mod}PackageInfo.checksum | sed 's/ //g')
            if [ "$X" != "$Y" ]; then
                checker="true"
                echo "PackageInfo.g in $mod have been modified"
                echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
            fi
        else
            checker="true"
            echo "Calculating md5sum for the package $mod";
            echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
        fi
    else
        echo "${mod} is not a valid package or does not exist in ${package_directory}";
    fi
done

for mod in ${extra_modules}; do
    if [ -r ${package_directory}/${mod}/PackageInfo.g ]; then
        X=$(md5sum ${package_directory}/${mod}/PackageInfo.g | sed 's/ //g')
        
        if [ -f ${DIR}/checksums/${mod}PackageInfo.checksum ]; then
            Y=$(cat ${DIR}/checksums/${mod}PackageInfo.checksum | sed 's/ //g')
            if [ "$X" != "$Y" ]; then
                checker="true"
                echo "PackageInfo.g in $mod have been modified"
                echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
            fi
        else
            checker="true"
            echo "Calculating md5sum for the package $mod";
            echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
        fi
    else
        echo "${mod} is not a valid package or does not exist in ${package_directory}";
    fi
done

if [ $checker ] || ! [  -e ${DIR}/checksums/homalg_workspace ]; then
    ${gap_bin} -b -r -R <<EOF
LoadPackage("io");
##This needs to be done better
xx:="${homalg_project_modules}";;
xx:=SplitString(xx," ");
for i in xx do
  LoadPackage( i );
od;
xx:="${extra_modules}";;
xx:=SplitString(xx," ");
for i in xx do
  LoadPackage( i );
od;
??blablfdfhskhks
function() local a; for a in NamesGVars() do if ISB_GVAR(a) then
VAL_GVAR(a); fi;od;end;
last();
SaveWorkspace("${DIR}/checksums/homalg_workspace");
quit;
EOF
fi
