#!/bin/bash

. ${DIR}/init_homalg_starter

checker=""

if [ -d ${pkg_dir}/pkg/homalg_project ]; then
    X=$(cd ${pkg_dir}/pkg/homalg_project; { git diff; git show; } | md5sum | sed 's/ //g')
    
    if [ -f ${DIR}/checksums/homalg_projectGitDiff.checksum ]; then
        Y=$(cat ${DIR}/checksums/homalg_projectGitDiff.checksum | sed 's/ //g')
        if [ "$X" != "$Y" ]; then
            checker="true"
                echo "'git diff' reported changes in homalg_project"
                echo $X > ${DIR}/checksums/homalg_projectGitDiff.checksum
        fi
    else
        checker="true"
        echo "Calculating md5sum for homalg_project";
        echo $X > ${DIR}/checksums/homalg_projectGitDiff.checksum
    fi
fi

for mod in ${extra_modules}; do
    if [ -d ${pkg_dir}/pkg/${mod} ]; then
        X=$(cd ${pkg_dir}/pkg/${mod}/; { git diff; git show; } | md5sum | sed 's/ //g')

        if [ -f ${DIR}/checksums/${mod}GitDiff.checksum ]; then
            Y=$(cat ${DIR}/checksums/${mod}GitDiff.checksum | sed 's/ //g')
            if [ "$X" != "$Y" ]; then
                checker="true"
                echo "'git diff' reported changes in the package $mod"
                echo $X > ${DIR}/checksums/${mod}GitDiff.checksum
            fi
        else
            checker="true"
            echo "Calculating md5sum for the package $mod";
            echo $X > ${DIR}/checksums/${mod}GitDiff.checksum
        fi
    else
        echo "${mod} is not a valid package or does not exist in ${pkg_dir}/pkg";
    fi
done

if [ $checker ] || ! [  -e ${DIR}/checksums/homalg_workspace_git ]; then
    ## we need the -r to have the history of the previous sessions
    ${gap_bin} -b -R -r -l "${pkg_dir};" ${DIR}/dostartforws_git.g
fi
