#!/bin/bash

. ${DIR}/init_homalg_starter

checker=""

for mod in ${homalg_modules}; do
    if [ -d ${package_directory}/${mod} ]; then
	X=$(md5sum ${package_directory}/${mod}/PackageInfo.g | sed 's/ //g')

	if [ -f ${DIR}/checksums/${mod}PackageInfo.checksum ]; then
	    Y=$(cat ${DIR}/checksums/${mod}PackageInfo.checksum | sed 's/ //g')
	    if [ "$X" != "$Y" ]; then
		checker="true"
		echo "PackageInfo.g in $mod have been modified"
		echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
	    fi
	else
	    checker="true"
	    echo "Calculating the checksum for the package $mod";
	    echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
	fi
    elif [ -d ${package_directory}/homalg_project/${mod} ]; then
	X=$(md5sum ${package_directory}/homalg_project/${mod}/PackageInfo.g | sed 's/ //g')

	if [ -f ${DIR}/checksums/${mod}PackageInfo.checksum ]; then
	    Y=$(cat ${DIR}/checksums/${mod}PackageInfo.checksum | sed 's/ //g')
	    if [ "$X" != "$Y" ]; then
		checker="true"
		echo "PackageInfo.g in $mod have been modified"
		echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
	    fi
	else
	    checker="true"
	    echo "Calculating the checksum for the package $mod";
	    echo $X > ${DIR}/checksums/${mod}PackageInfo.checksum
	fi
    else
	echo "${mod} is not a valid package or does not exist in ${package_directory}";
    fi
done

if [ $checker ] || ! [  -e ${DIR}/checksums/homalg_workspace ]; then
    ${gap_bin} -r -R <<EOF
LoadPackage("io");
##This needs to be done better
xx:="${homalg_modules}";
xx:=SplitString(xx," ");
for i in xx do
  LoadPackage( i );
od;
??blablfdfhskhks
function() local a; for a in NamesGVars() do if ISB_GVAR(a) then
VAL_GVAR(a); fi;od;end;
last();
SaveWorkspace("${DIR}/checksums/homalg_workspace");
quit;
EOF
fi

