#!/bin/bash

. ${DIR}/init_homalg_starter

checker=""

if [ -d ${package_directory}/homalg_project ]; then
    X=$(cd ${package_directory}/homalg_project; { git diff; git show; } | md5sum | sed 's/ //g')
    
    if [ -f ${DIR}/checksums/homalg_projectGitDiff.checksum ]; then
        Y=$(cat ${DIR}/checksums/homalg_projectGitDiff.checksum | sed 's/ //g')
        if [ "$X" != "$Y" ]; then
            checker="true"
                echo "'git diff' reported changes in the package $mod"
                echo $X > ${DIR}/checksums/homalg_projectGitDiff.checksum
        fi
    else
        checker="true"
        echo "Calculating md5sum for homalg_project";
        echo $X > ${DIR}/checksums/homalg_projectGitDiff.checksum
    fi
fi

for mod in ${extra_modules}; do
    if [ -d ${package_directory}/${mod} ]; then
        X=$(cd ${package_directory}/${mod}/; { git diff; git show; } | md5sum | sed 's/ //g')

        if [ -f ${DIR}/checksums/${mod}GitDiff.checksum ]; then
            Y=$(cat ${DIR}/checksums/${mod}GitDiff.checksum | sed 's/ //g')
            if [ "$X" != "$Y" ]; then
                checker="true"
                echo "'git diff' reported changes in the package $mod"
                echo $X > ${DIR}/checksums/${mod}GitDiff.checksum
            fi
        else
            checker="true"
            echo "Calculating md5sum for the package $mod";
            echo $X > ${DIR}/checksums/${mod}GitDiff.checksum
        fi
    else
        echo "${mod} is not a valid package or does not exist in ${package_directory}";
    fi
done

if [ $checker ] || ! [  -e ${DIR}/checksums/homalg_workspace_git ]; then
    ${gap_bin} -b -r -R <<EOF
LoadPackage("io");
##This needs to be done better
xx:="${homalg_project_modules}";;
xx:=SplitString(xx," ");
for i in xx do
  LoadPackage( i );
od;
xx:="${extra_modules}";;
xx:=SplitString(xx," ");
for i in xx do
  LoadPackage( i );
od;
??blablfdfhskhks
function() local a; for a in NamesGVars() do if ISB_GVAR(a) then
VAL_GVAR(a); fi;od;end;
last();
SaveWorkspace("${DIR}/checksums/homalg_workspace_git");
quit;
EOF
fi
